version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql-dev
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_PID: Developer
    volumes:
      - mssql_dev_data:/var/opt/mssql/data
      - ../util/Migrator:/mnt/migrator/
      - ./helpers/mssql:/mnt/helpers
      - ./.data/mssql:/mnt/data
    ports:
      - '1433:1433'

volumes:
  mssql_dev_data:
